In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import (
    SGDClassifier,
    SGDRegressor,
    LinearRegression,
    LogisticRegression,
)
from sklearn.datasets import make_regression, make_classification
import time

x_train, y_train = make_regression(
    n_samples=2000,
    n_features=1,
    n_informative=1,
    n_targets=1,
    noise=2,
    random_state=10,
)
x_test, y_test = make_regression(
    n_samples=2000, n_features=1, n_informative=1, n_targets=1, noise=1, random_state=10
)

# SGD

SGD has been successfully applied to large-scale and sparse machine learning problems often encountered in text classification and natural language processing. Given that the data is sparse, the classifiers in this module easily scale to problems with more than 10^5 training examples and more than 10^5 features.

The advantages of Stochastic Gradient Descent are:

- Efficiency.

- Easy of implementation (lots of opportunities for code tuning).

The disadvantages of Stochastic Gradient Descent include:

- SGD requires a number of hyperparameters such as the regularization parameter and the number of iterations.

- SGD is sensitive to feature scaling.

SGD Complexity: O(iter _ n_features _ m_samples)


# SGD Regression


In [81]:
SGD = SGDRegressor(
    loss="squared_error",
    penalty="elasticnet",
    alpha=0.00000001,
    l1_ratio=0.05,
    max_iter=10000000,
    learning_rate="invscaling",
)
SGD.fit(x_train, y_train)

SGDRegressor(alpha=1e-08, l1_ratio=0.05, max_iter=10000000,
             penalty='elasticnet')

In [82]:
SGD.coef_, SGD.intercept_, SGD.score(x_train, y_train), SGD.score(x_test, y_test)

(array([5.65756666]),
 array([0.00021596]),
 0.882097983094183,
 0.9678542266977391)

# SGD Classifier


In [174]:
x_train, y_train = make_classification(
    n_samples=10000,
    n_classes=2,
    random_state=10,
)
x_test, y_test = make_classification(n_samples=100, n_classes=2, random_state=10)

In [175]:
SGD = SGDClassifier(
    loss="modified_huber",
    penalty="elasticnet",
    alpha=0.0001,
    l1_ratio=0.005,
    max_iter=10000000,
    learning_rate="invscaling",
    eta0=1,
)
SGD.fit(x_train, y_train)

SGDClassifier(eta0=1, l1_ratio=0.005, learning_rate='invscaling',
              loss='modified_huber', max_iter=10000000, penalty='elasticnet')

In [176]:
SGD.coef_, SGD.intercept_, SGD.score(x_train, y_train), SGD.score(x_test, y_test)

(array([[-0.05740315, -0.01275681, -0.08467847,  0.08318247,  0.00981256,
         -0.04961965, -0.01112785, -0.02144157,  0.01942961, -0.02376868,
         -0.01998168, -0.14863181,  0.07020691, -0.00610284, -0.0078567 ,
          0.35129247, -0.01226661,  0.04092561,  0.80563615, -0.05475597]]),
 array([-0.06038874]),
 0.8939,
 0.9)